In [1]:
import requests
import pandas as pd
import json

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from math import sqrt

from scipy import stats
from pydataset import data
import Wrangle as w

In [2]:
df = pd.read_csv('final_steamspy_3000_games.csv', index_col = 0)

In [3]:
df

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu,appid.1,tags,genre
0,570,Dota 2,Valve,Valve,NaN,1587210,330303,0,"200,000,000 .. 500,000,000",40447,1560,976,1084,0,0,0,543171,570,"['Free to Play', 'MOBA', 'Multiplayer', 'Strategy', 'e-sports', 'Team-Based', 'Competi...","Action, Free to Play, Strategy"
1,730,Counter-Strike: Global Offensive,"Valve, Hidden Path Entertainment",Valve,NaN,6084096,801021,0,"50,000,000 .. 100,000,000",29608,771,6381,271,0,0,0,938203,730,"['FPS', 'Shooter', 'Multiplayer', 'Competitive', 'Action', 'Team-Based', 'e-sports', '...","Action, Free to Play"
2,578080,PUBG: BATTLEGROUNDS,"KRAFTON, Inc.","KRAFTON, Inc.",NaN,1214011,917768,0,"50,000,000 .. 100,000,000",22856,648,6688,189,0,0,0,324204,578080,"['Survival', 'Shooter', 'Battle Royale', 'Multiplayer', 'FPS', 'PvP', 'Third-Person Sh...","Action, Adventure, Free to Play, Massively Multiplayer"
3,1063730,New World,Amazon Games,Amazon Games,NaN,174544,75536,0,"50,000,000 .. 100,000,000",8257,1454,3567,1311,3999,3999,0,30922,1063730,"['Massively Multiplayer', 'Open World', 'MMORPG', 'RPG', 'Adventure', 'Action', 'PvP',...","Action, Adventure, Massively Multiplayer, RPG"
4,1172470,Apex Legends,Respawn Entertainment,Electronic Arts,NaN,483639,93045,0,"50,000,000 .. 100,000,000",6705,746,605,362,0,0,0,292023,1172470,"['Free to Play', 'Multiplayer', 'Battle Royale', 'Shooter', 'FPS', 'First-Person', 'Pv...","Action, Adventure, Free to Play"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,933820,Endzone - A World Apart,Gentlymad Studios,"Assemble Entertainment, WhisperGames",NaN,5951,1661,0,"200,000 .. 500,000",617,71,240,89,749,2999,75,339,933820,"['City Builder', 'Strategy', 'Survival', 'Post-apocalyptic', 'Simulation', 'Base-Build...","Indie, Simulation, Strategy"
2996,6550,Devil May Cry 3 Special Edition,"CAPCOM Co., Ltd.",Capcom,NaN,2077,1364,0,"200,000 .. 500,000",1890,0,61,0,1999,1999,0,13,6550,"['Action', 'Hack and Slash', 'Great Soundtrack', 'Spectacle fighter', 'Stylized', 'Cha...",Action
2997,1562420,FOREWARNED,Dreambyte Games,Dreambyte Games,NaN,3650,347,0,"200,000 .. 500,000",258,21,177,21,1299,1299,0,290,1562420,"['Horror', 'Online Co-Op', 'Survival Horror', 'Co-op', 'Multiplayer', 'Psychological H...","Action, Adventure, Indie, Early Access"
2998,945490,Little Square Things,G.Reed,Team3Studio,NaN,51,9,0,"200,000 .. 500,000",0,0,0,0,0,0,0,0,945490,"['Early Access', 'Indie', 'Strategy', 'Puzzle', 'Sokoban', 'Retro', 'Free to Play', 'T...","Indie, Strategy"
2999,99700,NightSky,"Nicalis, Inc.","Nicalis, Inc.",NaN,828,116,0,"200,000 .. 500,000",104,0,75,0,999,999,0,2,99700,"['Puzzle-Platformer', 'Indie', 'Platformer', 'Casual', 'Puzzle', 'Physics', 'Atmospher...","Casual, Indie, Strategy"

In [4]:
df = w.clean_steamspy(df)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3000 entries, 0 to 2999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            3000 non-null   int64
 1   name             3000 non-null   object
 2   developer        2987 non-null   object
 3   publisher        2997 non-null   object
 4   positive         3000 non-null   int64
 5   negative         3000 non-null   int64
 6   owners           3000 non-null   object
 7   average_forever  3000 non-null   float64
 8   average_2weeks   3000 non-null   float64
 9   median_forever   3000 non-null   float64
 10  median_2weeks    3000 non-null   float64
 11  price            3000 non-null   int64
 12  initialprice     3000 non-null   int64
 13  discount         3000 non-null   int64
 14  ccu              3000 non-null   int64
 15  appid.1          3000 non-null   int64
 16  tags             3000 non-null   object
 17  genre            2980 non-null   object
dtypes: float64(4), int64(8), object(6)
memory usage: 445.3+ KB

In [6]:
df.average_2weeks.value_counts()

0.000000    1817
0.008333      44
0.016667      17
0.050000      15
0.025000      13
            ...
9.583333       1
2.291667       1
3.433333       1
3.633333       1
5.491667       1
Name: average_2weeks, Length: 591, dtype: int64

In [7]:
df.average_forever.value_counts()

0.000000     136
1.400000       9
1.941667       9
1.275000       8
1.691667       8
            ...
13.758333      1
28.633333      1
11.491667      1
20.041667      1
27.191667      1
Name: average_forever, Length: 1567, dtype: int64

In [8]:
#df.discount.value_counts()

In [9]:
#df.score_rank.value_counts()

In [10]:
#df[df['average_2weeks']==0]

In [11]:
#df[df['average_2weeks']!=0]

In [12]:
df = df[df['average_forever']!=0]

In [22]:
#df.info()

In [21]:
#df[df.publisher.isnull() == True]

In [20]:
#df[df.genre.isnull() == True]

In [23]:
#df.dropna()

In [17]:
df = df.dropna()

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2846 entries, 0 to 2999
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            2846 non-null   int64
 1   name             2846 non-null   object
 2   developer        2846 non-null   object
 3   publisher        2846 non-null   object
 4   positive         2846 non-null   int64
 5   negative         2846 non-null   int64
 6   owners           2846 non-null   object
 7   average_forever  2846 non-null   float64
 8   average_2weeks   2846 non-null   float64
 9   median_forever   2846 non-null   float64
 10  median_2weeks    2846 non-null   float64
 11  price            2846 non-null   int64
 12  initialprice     2846 non-null   int64
 13  discount         2846 non-null   int64
 14  ccu              2846 non-null   int64
 15  appid.1          2846 non-null   int64
 16  tags             2846 non-null   object
 17  genre            2846 non-null   object
dtypes: float64(4), int64(8), object(6)
memory usage: 422.5+ KB

In [19]:
train, validate, test = w.my_train_test_split(df)

In [26]:
def get_tree(train_x, validate_x, train_y, validate_y):
    
    '''get decision tree accuracy on train and validate'''
    #create classifier then fit
    tree = DecisionTreeClassifier(max_depth=5, random_state=123)
    tree = tree.fit(train_x, train_y)

    print(f"Accuracy of Decision Tree on train data is {tree.score(train_x, train_y)}")
    print(f"Accuracy of Decision Tree on validate data is {tree.score(validate_x, validate_y)}")
    
#get_tree(train_x, validate_x, train_y, validate_y)


# ### rf

# In[24]:


def get_rf(train_x, validate_x, train_y, validate_y):

    '''get rf accuracy on train and validate'''
    #create classifier and fit
    rf = RandomForestClassifier(max_depth=5, random_state=123)
    rf = rf.fit(train_x, train_y)

    print(f"Accuracy of Random Forest on train data is {rf.score(train_x, train_y)}")
    print(f"Accuracy of Random Forest on validate data is {rf.score(validate_x, validate_y)}")


# ### regression

# In[25]:


def get_reg(train_x, validate_x, train_y, validate_y):

    '''get reg accuracy on train and validate'''
    #create classifier and fit
    logit = LogisticRegression(solver='liblinear')
    logit = logit.fit(train_x, train_y)

    print(f"Accuracy of Logistic Regression on train is {logit.score(train_x, train_y)}")
    print(f"Accuracy of Logistic Regression on validate is {logit.score(validate_x, validate_y)}")


# ### knn

# In[26]:


def get_knn(train_x, validate_x, train_y, validate_y):
    
    '''get knn accuracy on train and validate'''
    knn = KNeighborsClassifier(n_neighbors=5, weights='uniform')
    knn = knn.fit(train_x, train_y)

    # print results
    print(f"Accuracy of KNN on train is {knn.score(train_x, train_y)}")
    print(f"Accuracy of KNN on validate is {knn.score(validate_x, validate_y)}")